### ISSUE TITLE
Quaternion.from_axis_angle looks wrong

### ISSUE THREAD

**Issue by kd0aij** [PyFlightCoach/geometry#1]
https://github.com/PyFlightCoach/geometry/blob/44117dba9f976a09774f3c1758c68a47ffe4e48c/geometry/quaternion.py#L97

I don't get the same results with this as with the numpy quaternion package.

and what is the purpose of the factor parameter?

**Comment by ThomasDavid0** [comment]
Thanks, and good question! I'll investigate. Perhaps its best just to use the numpy operation here. This function is used a lot to generate template sequences, so this might explain why  the stall turns look wrong.

**Comment by ThomasDavid0** [comment]
Fixed with #2, thanks very much
